CREATE TABLE session (
    id_session INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status BOOLEAN,
    shift TEXT NOT NULL,
    id_laboratory INT NOT NULL,
    id_supervisor INT UNIQUE NOT NULL,
    FOREIGN KEY (id_laboratory) REFERENCES laboratory(id_laboratory),
    FOREIGN KEY (id_supervisor) REFERENCES supervisor(id_supervisor)
);